version: '3'
services:
  srv:
    image: orders_srv
    container_name: srv
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - db
    ports:
    - "8080:5000"

  db:
    container_name: db
    restart: unless-stopped
    build:
      context: ./db
    volumes:
    - orders-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}

    ports:
    - "33021:3306"

volumes:
  orders-data:
    driver: local